
services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    networks:
      - sailingLocNet
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  app:
    build: .
    container_name: app
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/sailingLoc?replicaSet=rs0
    command: sh -c "node wait-for-mongo.js && npx prisma db push && node index.js"
    volumes:
      - .:/app
    networks:
      - sailingLocNet

volumes:
  mongo_data:

networks:
  sailingLocNet:
    driver: bridge
